/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gia Severino
 */
import java.awt.*;
import javax.swing.JButton;
import javax.swing.JPanel;

public class HomeScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreen.class.getName());

    /**
     * Creates new form HomeScreen
     */
    
    public HomeScreen() {
    initComponents();
    
    // REMOVE ORIGINAL LABELS
    jPanel1.remove(jLabel4);
    jPanel1.remove(jLabel5);

    // ---- HERO CARD ----
    PanelRound heroCard = new PanelRound();
    heroCard.setRoundTopLeft(30);
    heroCard.setRoundTopRight(30);
    heroCard.setRoundBottomLeft(30);
    heroCard.setRoundBottomRight(30);
    heroCard.setBackground(new Color(20, 40, 70, 150));
    heroCard.setLayout(new GridBagLayout());
    // Add heroCard to jPanel1 using AbsoluteConstraints
    jPanel1.add(heroCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 540, 320));

    GridBagConstraints gbc = new GridBagConstraints();
    gbc.gridx = 0;
    //gbc.insets = new Insets(10, 20, 10, 20);
    gbc.anchor = GridBagConstraints.CENTER;

    // ---- ADD SHADOW TITLE ----
    ShadowLabel title = new ShadowLabel("E-LIGTAS");
    title.setFont(new Font("Century Gothic", Font.BOLD, 80));
    title.setShadowOffset(3, 3);
    title.setForeground(new Color(240, 240, 240));
    //heroCard.add(title, gbc);
    
    // Set insets for title (top, left, bottom, right)
    gbc.insets = new Insets(10, 20, 0, 20);  // Reduced bottom margin to 0
    heroCard.add(title, gbc);

    // ---- ADD SHADOW SUBTITLE ----
    ShadowLabel subtitle = new ShadowLabel("Centralized Emergency Reporting System");
    subtitle.setFont(new Font("Century Gothic", Font.ITALIC, 24));
    subtitle.setShadowOffset(2, 2);
    subtitle.setForeground(new Color(240, 240, 240));
    gbc.gridy = 1;
   // heroCard.add(subtitle, gbc);
   
    // Set insets for subtitle - reduce top margin to bring it closer to title
    gbc.gridy = 1;
    gbc.insets = new Insets(0, 20, 10, 20);  // Top margin is 0, bottom margin is 10
    heroCard.add(subtitle, gbc);
    
    // ---- BUTTONS PANEL ----
    JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 0));
    buttonPanel.setOpaque(false);
    
    // Remove original buttons from jPanel1 and add to buttonPanel
    jPanel1.remove(jButton2);  // Log In button
    jPanel1.remove(jButton1);  // Sign-Up button
    
    buttonPanel.add(jButton2);  // Add Log In first (left side)
    buttonPanel.add(jButton1);
    
    jButton2.setForeground(new Color(240, 240, 240));
    jButton1.setForeground(new Color(240, 240, 240));
    
    // Set insets for button panel - adjust top margin to position below subtitle
    gbc.gridy = 2;
    gbc.insets = new Insets(20, 20, 10, 20);  // Top margin 20, bottom margin 10
    heroCard.add(buttonPanel, gbc);

    // ENSURE BACKGROUND STAYS BEHIND EVERYTHING
    jPanel1.setComponentZOrder(jLabel1, jPanel1.getComponentCount() - 1);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 230, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(1053, 542));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/DICT_LOGO (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MIA_LGU_LOGO.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Centralized Emergency Reporting System");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("E-LIGTAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 400, 90));

        jButton1.setBackground(new java.awt.Color(12, 65, 96));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SIGN_IN (1).png"))); // NOI18N
        jButton1.setText("Sign-Up");
        jButton1.setActionCommand("");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 120, 40));

        jButton2.setBackground(new java.awt.Color(12, 65, 96));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-16.png"))); // NOI18N
        jButton2.setText("Log In");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HOMESCREEN_BG.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 540));
        jLabel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
